In [1]:
import pandas as pd
from sklearn.feature_selection import SelectKBest,chi2,SelectFromModel
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
import pickle

/Library/Python/2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
trng_data = pd.read_csv('training set values.csv')
trng_lbl = pd.read_csv('training set labels.csv')
trng_lbl['status_group'] = trng_lbl.status_group.map({'functional':0, 'functional needs repair':1, 'non functional':2})
data = pd.merge(trng_data,trng_lbl,how ='outer',on ='id')

In [3]:
X = pd.read_csv('training_cleaned_data_unscaled')
y = data['status_group']

In [11]:
clf = RandomForestClassifier()
clf = clf.fit(X, y)

In [12]:
clf.feature_importances_

array([ 0.03004632,  0.03500902,  0.05607067,  0.03001955,  0.09303708,
        0.09392765,  0.06698678,  0.0010858 ,  0.0107073 ,  0.06146229,
        0.01337157,  0.016693  ,  0.01515839,  0.02627678,  0.03965915,
        0.03697668,  0.01469737,  0.0063708 ,  0.02880246,  0.03376059,
        0.01674438,  0.02346156,  0.01194355,  0.1177026 ,  0.00920594,
        0.05915171,  0.051671  ])

In [13]:
model = SelectFromModel(clf, prefit=True)

In [14]:
X_new = model.transform(X)

In [15]:
X_new.shape

(59400, 9)

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size=0.3)

print "Data: ", data.shape
print "X_Train: ", X_train.shape
print "X_Test: ", X_test.shape
print "y_Train: ", y_train.shape
print "y_Test: : ", y_test.shape

Data:  (59400, 41)
X_Train:  (41580, 9)
X_Test:  (17820, 9)
y_Train:  (41580,)
y_Test: :  (17820,)


In [23]:
rc  = RandomForestClassifier(n_estimators=100,max_depth=20,max_features='sqrt')
rcp = rc.fit(X_train,y_train)

In [24]:
pred = rcp.predict(X_test)

In [27]:
print(classification_report(y_test,pred))
print ""
print ""
print(confusion_matrix(y_test,pred))
print ""
print ""
print(accuracy_score(y_test, pred))

             precision    recall  f1-score   support

          0       0.78      0.90      0.83      9745
          1       0.56      0.25      0.35      1282
          2       0.82      0.73      0.77      6793

avg / total       0.78      0.79      0.78     17820



[[8741  161  843]
 [ 731  323  228]
 [1750   88 4955]]


0.7867003367


/Users/rakesh/Library/Python/2.7/lib/python/site-packages/numpy/core/fromnumeric.py:2699: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)
