In [12]:
from xgboost import XGBClassifier

from sklearn.cross_validation import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

In [3]:
trng_data = pd.read_csv('training set values.csv')
trng_lbl = pd.read_csv('training set labels.csv')
trng_lbl['status_group'] = trng_lbl.status_group.map({'functional':0, 'functional needs repair':1, 'non functional':2})
data = pd.merge(trng_data,trng_lbl,how ='outer',on ='id')

#  Unscaled Data

In [37]:
X = pd.read_csv('training_cleaned_data_unscaled')
y = data['status_group']

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
print (X_train.shape)
print (X_test.shape)
print (y_train.shape)
print (y_test.shape)

(47520, 27)
(11880, 27)
(47520L,)
(11880L,)


In [39]:
clf = XGBClassifier(n_estimators=1000)

In [40]:
model = clf.fit(X_train,y_train)

In [41]:
pred = model.predict(X_test)

In [42]:
print classification_report(y_test,pred)
print ""
print confusion_matrix(y_test,pred)
print ""
accuracy_score(y_test,pred)

             precision    recall  f1-score   support

          0       0.76      0.91      0.83      6427
          1       0.64      0.22      0.33       875
          2       0.83      0.71      0.76      4578

avg / total       0.78      0.78      0.77     11880


[[5837   67  523]
 [ 540  195  140]
 [1299   42 3237]]



0.78021885521885526

# Scaled Data

In [23]:
X = pd.read_csv('training_cleaned_data')
y = data['status_group']

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
print (X_train.shape)
print (X_test.shape)
print (y_train.shape)
print (y_test.shape)

(47520, 27)
(11880, 27)
(47520L,)
(11880L,)


In [33]:
clf = XGBClassifier(n_estimators=1000,objective=)

In [34]:
model = clf.fit(X_train,y_train)

In [35]:
pred = model.predict(X_test)

In [36]:
print classification_report(y_test,pred)
print ""
print confusion_matrix(y_test,pred)
print ""
accuracy_score(y_test,pred)

             precision    recall  f1-score   support

          0       0.76      0.91      0.83      6460
          1       0.68      0.22      0.33       873
          2       0.83      0.71      0.77      4547

avg / total       0.78      0.78      0.77     11880


[[5858   66  536]
 [ 559  188  126]
 [1289   23 3235]]



0.78122895622895627